version: '3.8'

services:
  hapi-fhir:
    image: hapiproject/hapi:latest
    container_name: plumly-hapi-fhir
    ports:
      - "8080:8080"
    environment:
      - hapi.fhir.server_address=http://localhost:8080/fhir/
      - hapi.fhir.tester_config_url=/data/config/test_config.json
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.allow_placeholder_references=true
      - hapi.fhir.enforce_referential_integrity_on_write=false
      - hapi.fhir.enforce_referential_integrity_on_delete=false
    volumes:
      - hapi_data:/data/hapi
      - ./docker/hapi-config:/data/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/fhir/metadata"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  hapi_data: